# Euler 45
# http://projecteuler.net/index.php?section=problems&id=45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

require 'benchmark'
require File.expand_path(File.dirname(__FILE__)) + '/../lib/integer_shapes.rb'

time = Benchmark.realtime do
  triangles, pentagons, hexagons = [], [], []
  1.upto(100000) { |i|
    triangles << i.triangular
    pentagons << i.pentagonal
    hexagons << i.hexagonal
  }

  #The first is 1, the second is 40755, per the question. Return the next one since there could be more
  @answer = (triangles & pentagons & hexagons)[2]
end
puts "Euler 45: #{@answer}\t#{time*1000} milliseconds"
